version: '3'

services:
  weather-api:
    build:
      context: .
      args:
        SERVICE_NAME: weather-api
    container_name: weather-api
    ports:
      - 8080:8080
    networks:
      - app-network
      
  zipcode-api:
    build:
      context: .
      args:
        SERVICE_NAME: zipcode-api
    container_name: zipcode-api
    ports:
      - 8081:8081
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge